"""add category_scores to compliance_runs

Revision ID: 7f1a8f8d0873
Revises: 8bf417ace640
Create Date: 2026-09-29 12:02:28.991209
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7f1a8f8d0873'
down_revision: Union[str, None] = '8bf417ace640'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('compliance_runs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_scores', sa.JSON(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('compliance_runs', schema=None) as batch_op:
        batch_op.drop_column('category_scores')

    # ### end Alembic commands ###
