"""initial schema

Revision ID: 8bf417ace640
Revises: 
Create Date: 2026-09-29 11:39:14.837808
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '8bf417ace640'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compliance_rules',
    sa.Column('rule_id', sa.String(length=60), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('target_field', sa.String(length=160), nullable=False),
    sa.Column('operator', sa.String(length=30), nullable=False),
    sa.Column('expected_value', sa.String(length=200), nullable=True),
    sa.Column('on_missing', sa.String(length=10), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('compliance_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_compliance_rules_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_compliance_rules_rule_id'), ['rule_id'], unique=True)

    op.create_table('frameworks',
    sa.Column('key', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('version', sa.String(length=40), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('frameworks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_frameworks_key'), ['key'], unique=True)

    op.create_table('organizations',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('analysis_jobs',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('job_type', sa.String(length=40), nullable=False),
    sa.Column('resource_type', sa.String(length=40), nullable=False),
    sa.Column('resource_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('current_stage', sa.String(length=60), nullable=True),
    sa.Column('stages', sa.JSON(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analysis_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analysis_jobs_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_analysis_jobs_resource_id'), ['resource_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_analysis_jobs_status'), ['status'], unique=False)

    op.create_table('audit_logs',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=60), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('actor', sa.String(length=255), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('device_id', sa.String(length=36), nullable=True),
    sa.Column('configuration_id', sa.String(length=36), nullable=True),
    sa.Column('finding_id', sa.String(length=36), nullable=True),
    sa.Column('report_id', sa.String(length=36), nullable=True),
    sa.Column('pattern_id', sa.String(length=36), nullable=True),
    sa.Column('job_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_configuration_id'), ['configuration_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_device_id'), ['device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_finding_id'), ['finding_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_pattern_id'), ['pattern_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_report_id'), ['report_id'], unique=False)

    op.create_table('devices',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=False),
    sa.Column('vendor', sa.String(length=60), nullable=False),
    sa.Column('device_type', sa.String(length=40), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=True),
    sa.Column('serial_number', sa.String(length=120), nullable=True),
    sa.Column('os_name', sa.String(length=60), nullable=True),
    sa.Column('os_version', sa.String(length=60), nullable=True),
    sa.Column('firmware_version', sa.String(length=60), nullable=True),
    sa.Column('management_ip', sa.String(length=64), nullable=True),
    sa.Column('location', sa.String(length=160), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('compliance_score', sa.Integer(), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('last_analysis_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_devices_hostname'), ['hostname'], unique=False)
        batch_op.create_index(batch_op.f('ix_devices_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_devices_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_devices_vendor'), ['vendor'], unique=False)

    op.create_table('framework_mappings',
    sa.Column('rule_id', sa.String(length=60), nullable=False),
    sa.Column('framework_key', sa.String(length=20), nullable=False),
    sa.Column('control_id', sa.String(length=60), nullable=False),
    sa.Column('control_title', sa.String(length=255), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['compliance_rules.rule_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('framework_mappings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_framework_mappings_framework_key'), ['framework_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_framework_mappings_rule_id'), ['rule_id'], unique=False)

    op.create_table('reports',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('format', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('device_ids', sa.JSON(), nullable=False),
    sa.Column('compliance_score', sa.Integer(), nullable=False),
    sa.Column('findings_count', sa.Integer(), nullable=False),
    sa.Column('severity_breakdown', sa.JSON(), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=True),
    sa.Column('preview', sa.JSON(), nullable=False),
    sa.Column('generated_by', sa.String(length=255), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reports_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_status'), ['status'], unique=False)

    op.create_table('training_patterns',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('vendor', sa.String(length=60), nullable=False),
    sa.Column('os', sa.String(length=60), nullable=True),
    sa.Column('raw_pattern', sa.Text(), nullable=False),
    sa.Column('normalized_field', sa.String(length=160), nullable=True),
    sa.Column('security_category', sa.String(length=40), nullable=True),
    sa.Column('extraction_strategy', sa.String(length=60), nullable=True),
    sa.Column('ai_confidence', sa.Double(), nullable=False),
    sa.Column('human_confidence', sa.Double(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('approved_by', sa.String(length=255), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_note', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('training_patterns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_training_patterns_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_training_patterns_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_training_patterns_vendor'), ['vendor'], unique=False)

    op.create_table('users',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('role', sa.String(length=40), nullable=False),
    sa.Column('auth_subject', sa.String(length=255), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'email', name='uq_user_org_email')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_auth_subject'), ['auth_subject'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_organization_id'), ['organization_id'], unique=False)

    op.create_table('ai_analysis',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('pattern_id', sa.String(length=36), nullable=True),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('interpretation', sa.Text(), nullable=True),
    sa.Column('suggested_category', sa.String(length=40), nullable=True),
    sa.Column('suggested_field', sa.String(length=160), nullable=True),
    sa.Column('confidence', sa.Double(), nullable=False),
    sa.Column('similar_patterns', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pattern_id'], ['training_patterns.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_analysis', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_analysis_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_analysis_pattern_id'), ['pattern_id'], unique=False)

    op.create_table('configurations',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('device_id', sa.String(length=36), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.String(length=10), nullable=False),
    sa.Column('configuration_version', sa.String(length=60), nullable=True),
    sa.Column('raw_storage_path', sa.String(length=500), nullable=True),
    sa.Column('sanitized_content', sa.Text(), nullable=True),
    sa.Column('line_count', sa.Integer(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('detected_vendor', sa.String(length=60), nullable=True),
    sa.Column('detected_os', sa.String(length=60), nullable=True),
    sa.Column('detection_confidence', sa.Double(), nullable=False),
    sa.Column('syntax_style', sa.String(length=20), nullable=True),
    sa.Column('parser_status', sa.String(length=20), nullable=False),
    sa.Column('normalization_status', sa.String(length=20), nullable=False),
    sa.Column('analysis_status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('configurations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_configurations_analysis_status'), ['analysis_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_configurations_detected_vendor'), ['detected_vendor'], unique=False)
        batch_op.create_index(batch_op.f('ix_configurations_device_id'), ['device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_configurations_organization_id'), ['organization_id'], unique=False)

    op.create_table('device_credential_refs',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('device_id', sa.String(length=36), nullable=False),
    sa.Column('method', sa.String(length=20), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=True),
    sa.Column('credential_reference', sa.String(length=255), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('device_credential_refs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_device_credential_refs_device_id'), ['device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_device_credential_refs_organization_id'), ['organization_id'], unique=False)

    op.create_table('training_feedback',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('pattern_id', sa.String(length=36), nullable=False),
    sa.Column('decision', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=True),
    sa.Column('field', sa.String(length=160), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('actor', sa.String(length=255), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pattern_id'], ['training_patterns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('training_feedback', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_training_feedback_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_training_feedback_pattern_id'), ['pattern_id'], unique=False)

    op.create_table('compliance_runs',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('device_id', sa.String(length=36), nullable=False),
    sa.Column('configuration_id', sa.String(length=36), nullable=False),
    sa.Column('overall_score', sa.Integer(), nullable=False),
    sa.Column('total_rules', sa.Integer(), nullable=False),
    sa.Column('passed', sa.Integer(), nullable=False),
    sa.Column('failed', sa.Integer(), nullable=False),
    sa.Column('not_applicable', sa.Integer(), nullable=False),
    sa.Column('unknown', sa.Integer(), nullable=False),
    sa.Column('framework_scores', sa.JSON(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['configuration_id'], ['configurations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('compliance_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_compliance_runs_configuration_id'), ['configuration_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_compliance_runs_device_id'), ['device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_compliance_runs_organization_id'), ['organization_id'], unique=False)

    op.create_table('normalized_configurations',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('configuration_id', sa.String(length=36), nullable=False),
    sa.Column('model', sa.JSON(), nullable=False),
    sa.Column('schema_version', sa.String(length=20), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['configuration_id'], ['configurations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('normalized_configurations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_normalized_configurations_configuration_id'), ['configuration_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_normalized_configurations_organization_id'), ['organization_id'], unique=False)

    op.create_table('normalized_facts',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('configuration_id', sa.String(length=36), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('field', sa.String(length=160), nullable=False),
    sa.Column('label', sa.String(length=160), nullable=False),
    sa.Column('value', sa.String(length=500), nullable=False),
    sa.Column('value_type', sa.String(length=20), nullable=False),
    sa.Column('origin', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Double(), nullable=False),
    sa.Column('line_start', sa.Integer(), nullable=True),
    sa.Column('line_end', sa.Integer(), nullable=True),
    sa.Column('snippet', sa.String(length=500), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['configuration_id'], ['configurations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('normalized_facts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_normalized_facts_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_normalized_facts_configuration_id'), ['configuration_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_normalized_facts_field'), ['field'], unique=False)
        batch_op.create_index(batch_op.f('ix_normalized_facts_organization_id'), ['organization_id'], unique=False)

    op.create_table('findings',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('device_id', sa.String(length=36), nullable=False),
    sa.Column('configuration_id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=True),
    sa.Column('rule_id', sa.String(length=60), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('result', sa.String(length=10), nullable=False),
    sa.Column('actual_value', sa.String(length=500), nullable=True),
    sa.Column('expected_value', sa.String(length=500), nullable=True),
    sa.Column('security_impact', sa.Text(), nullable=True),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('frameworks', sa.JSON(), nullable=False),
    sa.Column('verification', sa.JSON(), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['configuration_id'], ['configurations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['compliance_runs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('findings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_findings_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_findings_configuration_id'), ['configuration_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_findings_device_id'), ['device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_findings_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_findings_rule_id'), ['rule_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_findings_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_findings_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_findings_status'), ['status'], unique=False)

    op.create_table('remediations',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('finding_id', sa.String(length=36), nullable=False),
    sa.Column('device_id', sa.String(length=36), nullable=False),
    sa.Column('vendor', sa.String(length=60), nullable=False),
    sa.Column('os', sa.String(length=60), nullable=True),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('current_config', sa.Text(), nullable=True),
    sa.Column('expected_config', sa.Text(), nullable=True),
    sa.Column('commands', sa.JSON(), nullable=False),
    sa.Column('verification_steps', sa.JSON(), nullable=False),
    sa.Column('rollback_steps', sa.JSON(), nullable=False),
    sa.Column('disruptive', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('approval', sa.String(length=20), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('remediations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_remediations_device_id'), ['device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_remediations_finding_id'), ['finding_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_remediations_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_remediations_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_remediations_vendor'), ['vendor'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('remediations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_remediations_vendor'))
        batch_op.drop_index(batch_op.f('ix_remediations_status'))
        batch_op.drop_index(batch_op.f('ix_remediations_organization_id'))
        batch_op.drop_index(batch_op.f('ix_remediations_finding_id'))
        batch_op.drop_index(batch_op.f('ix_remediations_device_id'))

    op.drop_table('remediations')
    with op.batch_alter_table('findings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_findings_status'))
        batch_op.drop_index(batch_op.f('ix_findings_severity'))
        batch_op.drop_index(batch_op.f('ix_findings_run_id'))
        batch_op.drop_index(batch_op.f('ix_findings_rule_id'))
        batch_op.drop_index(batch_op.f('ix_findings_organization_id'))
        batch_op.drop_index(batch_op.f('ix_findings_device_id'))
        batch_op.drop_index(batch_op.f('ix_findings_configuration_id'))
        batch_op.drop_index(batch_op.f('ix_findings_category'))

    op.drop_table('findings')
    with op.batch_alter_table('normalized_facts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_normalized_facts_organization_id'))
        batch_op.drop_index(batch_op.f('ix_normalized_facts_field'))
        batch_op.drop_index(batch_op.f('ix_normalized_facts_configuration_id'))
        batch_op.drop_index(batch_op.f('ix_normalized_facts_category'))

    op.drop_table('normalized_facts')
    with op.batch_alter_table('normalized_configurations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_normalized_configurations_organization_id'))
        batch_op.drop_index(batch_op.f('ix_normalized_configurations_configuration_id'))

    op.drop_table('normalized_configurations')
    with op.batch_alter_table('compliance_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_compliance_runs_organization_id'))
        batch_op.drop_index(batch_op.f('ix_compliance_runs_device_id'))
        batch_op.drop_index(batch_op.f('ix_compliance_runs_configuration_id'))

    op.drop_table('compliance_runs')
    with op.batch_alter_table('training_feedback', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_training_feedback_pattern_id'))
        batch_op.drop_index(batch_op.f('ix_training_feedback_organization_id'))

    op.drop_table('training_feedback')
    with op.batch_alter_table('device_credential_refs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_device_credential_refs_organization_id'))
        batch_op.drop_index(batch_op.f('ix_device_credential_refs_device_id'))

    op.drop_table('device_credential_refs')
    with op.batch_alter_table('configurations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_configurations_organization_id'))
        batch_op.drop_index(batch_op.f('ix_configurations_device_id'))
        batch_op.drop_index(batch_op.f('ix_configurations_detected_vendor'))
        batch_op.drop_index(batch_op.f('ix_configurations_analysis_status'))

    op.drop_table('configurations')
    with op.batch_alter_table('ai_analysis', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_analysis_pattern_id'))
        batch_op.drop_index(batch_op.f('ix_ai_analysis_organization_id'))

    op.drop_table('ai_analysis')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_organization_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index(batch_op.f('ix_users_auth_subject'))

    op.drop_table('users')
    with op.batch_alter_table('training_patterns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_training_patterns_vendor'))
        batch_op.drop_index(batch_op.f('ix_training_patterns_status'))
        batch_op.drop_index(batch_op.f('ix_training_patterns_organization_id'))

    op.drop_table('training_patterns')
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reports_status'))
        batch_op.drop_index(batch_op.f('ix_reports_organization_id'))

    op.drop_table('reports')
    with op.batch_alter_table('framework_mappings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_framework_mappings_rule_id'))
        batch_op.drop_index(batch_op.f('ix_framework_mappings_framework_key'))

    op.drop_table('framework_mappings')
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_devices_vendor'))
        batch_op.drop_index(batch_op.f('ix_devices_status'))
        batch_op.drop_index(batch_op.f('ix_devices_organization_id'))
        batch_op.drop_index(batch_op.f('ix_devices_hostname'))

    op.drop_table('devices')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_report_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_pattern_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_organization_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_job_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_finding_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_event_type'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_device_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_configuration_id'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('analysis_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analysis_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_analysis_jobs_resource_id'))
        batch_op.drop_index(batch_op.f('ix_analysis_jobs_organization_id'))

    op.drop_table('analysis_jobs')
    op.drop_table('organizations')
    with op.batch_alter_table('frameworks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_frameworks_key'))

    op.drop_table('frameworks')
    with op.batch_alter_table('compliance_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_compliance_rules_rule_id'))
        batch_op.drop_index(batch_op.f('ix_compliance_rules_category'))

    op.drop_table('compliance_rules')
    # ### end Alembic commands ###
